### ISSUE TITLE
Hard stop 100%

### ISSUE THREAD

**Issue by grxnola** [joue-quroi/adjust-screen-brightness#13]
The add-on was fine before the latest update, which now requires micro-adjusting the handle to set brightness at 100%. This is a downgrade in usability.

**Comment by joue-quroi** [comment]
I added 20% ticks for both progress elements. Unfortunately, it is not yet supported on Firefox. On Firefox, for now, adjust it to any number close to 100%, then press the Shift + Left or Right arrow keys.

**Comment by grxnola** [comment]
I shall use the shortcut, appreciated.
