### ISSUE TITLE
Increase brightness beyond 100%

### ISSUE THREAD

**Issue by ghost** [joue-quroi/adjust-screen-brightness#2]
It would be nice to be able to increase the brightness beyond 100%. It would be useful when streaming videos that are too dark.

**Comment by joue-quroi** [comment]
As far as I know there is no CSS for this.

**Comment by arjittw** [comment]
Maybe brightness filter
``` css
filter: brightness(120%);
```

**Comment by joue-quroi** [comment]
Thanks, @arjittw. The new release now uses the brightness filter by default. There is an option to switch back to the old method. Hopefully, it is not conflicting with too many default website themes.
