### ISSUE TITLE
Document how to have different levels for different computers despite chrome sync

### ISSUE THREAD

**Issue by jidanni** [joue-quroi/adjust-screen-brightness#3]
If the user has Chrome sync enabled, the extension will be installed on all his computers.
That is good, but not all his computers have the exact same brightness problems he wishes to correct.

In the instructions please mention how the user can maintain different levels for his computer A vs. his computer B.

**Comment by joue-quroi** [comment]
Version 0.1.3 uses the local storage so you can have your own custom settings for each browser.
