### ISSUE TITLE
Add control to temporarily disable for this page/site

### ISSUE THREAD

**Issue by jidanni** [joue-quroi/adjust-screen-brightness#5]
The icon is currently a black wheel with a dot in the middle.
It should instead be a colored wheel with a dot in the middle.
The black and white version should be reserved to indicate "disabled for this page/site."
And indeed, there should be a way, to temporarily disable the extension for this page/site,
short of having to mess with the sliders or uninstall the extension.

**Comment by joue-quroi** [comment]
Thanks for the report. There are two new buttons on version 0.1.3 which allow you to toggle the extension on and off in the current hostname.
