### ISSUE TITLE
Clicking a second time should make the slider menu disappear

### ISSUE THREAD

**Issue by jidanni** [joue-quroi/adjust-screen-brightness#6]
Clicking the eyeball icon pops up the two slider menu.
Clicking a second time should make the menu disappear.
Yes, even though he can click elsewhere to make it disappear.

**Comment by joue-quroi** [comment]
This is the default behavior of most browsers. Note that no extension has control over the outside boundaries of its popup. So there is nothing we can do unless the browser fixes the bug.
