### ISSUE TITLE
Can we have brightness for a website feature

### ISSUE THREAD

**Issue by sergeByishimo** [joue-quroi/adjust-screen-brightness#9]
Love the extension, i use it all the time!

but i was wondering if we can set specific brightness for specific websites, like some websites which are already in dark mode, it would help a lot!

coz i find myself changing brightness every time i'm on a dark mode website! 

Regards,

**Comment by arjittw** [comment]
Some websites needs to dim a little while some a lot.
If any option to enable here only like something?
